// add new lectures to the top 
// use html syntax
var lectures = [
	"<p><b>4/10/2019 - Writing Systems</b></p><p>Today's lecture was on the types of writing systems, such as alphabets, abjads, abugidas, and syllabaries.</p><ul><li><a href=\"https://slides.com/wjeng/uniling06\">Today's presentation</a></li><li><a href=\"https://www.omniglot.com/writing/index.htm\">Omniglot</a>, a neat website with many language facts, such as writing systems.</li></ul>",
	"<p><b>3/27/2019 - Language Variation</b></p><p>Today's lecture was on language variation, more specifically dialects.</p><ul><li><a href=\"https://slides.com/wjeng/uniling05\">Today's presentation</a></li><li><a href=\"https://www.youtube.com/watch?v=fj4w6SCn2ZM\">A video of a story being told in Ulster Scots, a dialect/language spoken in Northern Ireland.</a></li></ul>",
	"<p><b>3/13/2019 - Linguistics Puzzle (Japanese Braille)</b></p> <p>Today we did a linguistics puzzle involving Japanese Braille, or <i>tenji</i>. The problem can be found <a href=\"http://nacloweb.org/resources/problems/2009/N2009-A.pdf\">here</a> and the solution can be found <a href=\"http://nacloweb.org/resources/problems/2009/N2009-AS.pdf\">here</a>.</p>",
	"<p><b>3/6/2019 - Number Systems</b></p><p>Today's lecture was on number systems, including number bases and large numbers.</p><ul><li><a href=\"https://slides.com/wjeng/uniling03\">Today's presentation</a></li><li><a href=\"https://www.nacloweb.org/resources/problems/2017/N2017-G.pdf\">Magik Yup'ik - A number problem from NACLO 2017 Open Round</a></li><li><a href=\"http://nacloweb.org/resources/problems/2017/N2017-GS.pdf\">Solution to Magik Yup'ik</a></li></ul>",
	"<p><b>2/27/2019 - The International Phonetic Alphabet</b></p>\n<p>Today's lecture was on the IPA, which served as an introduction to phonetics. Below are some resources used today.</p>\n<ul><li><a href=\"https://slides.com/wjeng/uniling02\">Todays's presentation</a></li><li><a href=\"http://www.ipachart.com/\">An interactive IPA chart</a></li><li><a href=\"https://www.youtube.com/watch?v=W6WO5XabD-s\">YouTube video of a man speaking in a language with clicks</a></li><li><a href=\"https://www.youtube.com/watch?v=-zB2TG9sVf8\">A nice video by NativLang on weird phonemes</a></li><li><a href=\"https://www.nacloweb.org/resources/problems/2012/N2012-H.pdf\">Waorani: a puzzle on number systems</a> (<a href=\"https://www.nacloweb.org/resources/problems/2012/N2012-HS.pdf\">solution</a>)</li></ul>",
	"<p><b>2/20/2019 - Introduction to Linguistics</b></p>\n<p>Thank you to everyone who came to our first club meeting! We discussed the subfields of linguistics and made an introduction to linguistic puzzles.<br\>Today's presentation can be found <a href=\"https://slides.com/wjeng/uniling01\">here</a>.</p>\n"
];
